version: 2

# What is this - http://yaml.org/type/merge.html
defaults: &defaults
  docker:
    - image: circleci/node:9.3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn cache
          key: node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install modules
          command: yarn --frozen-lockfile install
      - save_cache:
          name: Save yarn cache
          key: node-modules--{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Building
          command: yarn build
      - persist_to_workspace:
          root: ../
          paths:
            - project/

  # Docker steps
  # These steps have a different workspace roots and so will behave a bit differently
  # circleci/node has /users/circleci/project
  # civilmedia/gcloud-node has /root/project
  setup-gcp:
    <<: *defaults
    docker:
      - image: civilmedia/gcloud-node:latest
    steps:
      - run:
          name: Dump Google Cloud Credentials to file
          command: |
            echo ${GOOGLE_AUTH} | base64 -d > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            gcloud docker --authorize-only
      - persist_to_workspace:
          root: /root
          paths:
            - gcp-key.json
            - .config/gcloud
            - .docker
            - .dockercfg
            - .kubernetes_ns
            - .kube

  push-containers:
    <<: *defaults
    docker:
      - image: civilmedia/gcloud-node:latest
    steps:
      - checkout
      - attach_workspace:
          at: /root
      - setup_remote_docker
      - run:
          name: Build Container
          command: |
            TAG=`echo $CIRCLE_BRANCH | sed 's/\\//_/g'`
            docker build -f Dockerfile-dapp . \
            -t gcr.io/$GOOGLE_PROJECT_ID/dapp:$TAG \
            -t gcr.io/$GOOGLE_PROJECT_ID/dapp:$TAG-$CIRCLE_SHA1
      - deploy:
          name: Push Containers to Registry
          command: |
            gcloud config list
            echo "pushing $GOOGLE_PROJECT_ID"
            docker push gcr.io/$GOOGLE_PROJECT_ID/dapp

  deploy-staging:
    <<: *defaults
    docker:
      - image: civilmedia/gcloud-node:latest
    steps:
      - attach_workspace:
          at: /root
      - deploy:
          name: Update Kubernetes Deployment on STAGING
          command: |
            kubectl set image deployment/dapp dapp=gcr.io/$GOOGLE_PROJECT_ID/dapp:master-$CIRCLE_SHA1 --namespace staging

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *" # Midnight UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - coverage:
          requires:
            - build
  pull-request:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - test:
          filters:
            branches:
              ignore:
                - master
          requires:
            - build
      - lint:
          filters:
            branches:
              ignore:
                - master
          requires:
            - build
  staging:
    jobs:
      - setup-gcp:
          context: gcp-common
          filters:
            branches:
              only:
                - master
      - push-containers:
          context: gcp-common
          requires:
            - setup-gcp
          filters:
            branches:
              only:
                - master
      - deploy-staging:
          context: gcp-common
          requires:
            - push-containers
          filters:
            branches:
              only:
                - master
